# Generated by Django 3.2.9 on 2021-12-16 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(related_name='like_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
