# Generated by Django 3.2.9 on 2021-12-16 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0006_alter_article_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
